version: "3"
services:
  base:
    image: node:13.12.0-alpine
    volumes:
      - .:/usr/sandbox
    working_dir: /usr/sandbox
    ports:
      - 3000:3000
      - 9229:9229
  install:
    extends:
      service: base
    command: npm i
  dev:
    extends:
      service: install
    command: npm run dev
